//
//  Salesman.swift
//  AmadaMachines
//
//  Created by IT Support on 9/12/19.
//  Copyright © 2019 IT Support. All rights reserved.
//

import Foundation

struct AS400_SALESMAN {
    public var SalesmanNumber: Int
    public var FirstName: String
    public var LastName: String
    public var Email: String

    init(SalesmanNumber: Int, FirstName: String, LastName: String, Email: String) {
        self.SalesmanNumber = SalesmanNumber
        self.FirstName = FirstName
        self.LastName = LastName
        self.Email = Email
    }

    init() {
        self.SalesmanNumber = 0
        self.FirstName = ""
        self.LastName = ""
        self.Email = ""
    }

    init(_ coreModel: SalesmanCore) {
        self.SalesmanNumber = Int(coreModel.salesmanNumber)
        self.FirstName = coreModel.firstName ?? ""
        self.LastName = coreModel.lastName ?? ""
        self.Email = coreModel.email ?? ""
    }

    func getSalesman() -> [AS400_SALESMAN] {
        return [
            AS400_SALESMAN(SalesmanNumber:01141,FirstName:"Mark",LastName:"Abrook",Email:"mabrook@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01463,FirstName:"Matthew",LastName:"Adkison",Email:"madkison@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01295,FirstName:"Armando",LastName:"Aguilar",Email:"aaguilar@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00619,FirstName:"Bob",LastName:"Aitken",Email:"baitken@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01189,FirstName:"Scott",LastName:"Aitken",Email:"saitken@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01391,FirstName:"Eileen",LastName:"Alanis",Email:"ealanis@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01154,FirstName:"Michael",LastName:"Albert",Email:"malbert@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00966,FirstName:"Themis",LastName:"Alexopoulos",Email:"talexopoulos@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01239,FirstName:"Christian",LastName:"Altamirano",Email:"caltamirano@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01455,FirstName:"Ryan",LastName:"Alvarez",Email:"ryanalvarez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00928,FirstName:"Craig",LastName:"Amedeo",Email:"camedeo@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01243,FirstName:"Nicole",LastName:"Amico",Email:"namico@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01373,FirstName:"Sherri",LastName:"Anderson",Email:"sanderson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01135,FirstName:"Amado",LastName:"Andujo",Email:"amado@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01093,FirstName:"Abraham",LastName:"Andujo",Email:"aandujo@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01147,FirstName:"George",LastName:"Angelacos",Email:"gangelacos@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01413,FirstName:"Randall",LastName:"Anstaett",Email:"ranstaett@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01339,FirstName:"Nolan",LastName:"Antonoff",Email:"nantonoff@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01409,FirstName:"Israel",LastName:"Arenas",Email:"iarenas@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01278,FirstName:"Carlos",LastName:"Arias",Email:"carias@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06007,FirstName:"Mario",LastName:"Ayotte",Email:"ayotte@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01447,FirstName:"William",LastName:"Baillargeon",Email:"wbaillargeon@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01411,FirstName:"Joseph",LastName:"Bardon",Email:"jbardon@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01117,FirstName:"Tim",LastName:"Barefoot",Email:"tbarefoot@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01432,FirstName:"Cody",LastName:"Bargdill",Email:"cbargdill@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01027,FirstName:"Herman",LastName:"Barron",Email:"hbarron@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01241,FirstName:"Bryan",LastName:"Barry",Email:"bbarry@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00930,FirstName:"Steve",LastName:"Bartuce",Email:"sbartuce@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06004,FirstName:"Sarab",LastName:"Basran",Email:"sbasran@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01142,FirstName:"Jevon",LastName:"Bauman",Email:"jbauman@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01438,FirstName:"Juan Pablo",LastName:"Beas",Email:"jpbeas@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00916,FirstName:"Greg",LastName:"Beaudoin",Email:"gbeaudoin@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06008,FirstName:"Richard",LastName:"Bedford",Email:"rbedford@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:06005,FirstName:"Guy",LastName:"Beique",Email:"gbeique@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01176,FirstName:"Dan",LastName:"Belz",Email:"dbelz@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01349,FirstName:"Chase",LastName:"Benjamin",Email:"cbenjamin@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00942,FirstName:"Rob",LastName:"Benoit",Email:"rbenoit@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01232,FirstName:"Brent",LastName:"Bilhartz",Email:"bbilhartz@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01442,FirstName:"Jeffrey",LastName:"Bloechle",Email:"jbloechle@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01115,FirstName:"Mike",LastName:"Bloss",Email:"mbloss@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01288,FirstName:"Doug",LastName:"Bowen",Email:"dbowen@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00953,FirstName:"Scott",LastName:"Bowerman",Email:"sbowerman@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01294,FirstName:"Evandole",LastName:"Boyol",Email:"eboyol@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01122,FirstName:"Tim",LastName:"Brady",Email:"tbrady@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01209,FirstName:"Lisa",LastName:"Brockhoeft",Email:"lbrockhoeft@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01382,FirstName:"Sarah",LastName:"Brown",Email:"sarahbrown@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01225,FirstName:"Eric",LastName:"Burdi",Email:"eburdi@amada.com"),
            AS400_SALESMAN(SalesmanNumber:05362,FirstName:"Colin",LastName:"Butler",Email:"cbutler@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01381,FirstName:"Dustin",LastName:"Campbell",Email:"dcampbell@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01328,FirstName:"Sergio",LastName:"Cano",Email:"scano@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01351,FirstName:"Sergio",LastName:"Cano Jr.",Email:"sergiocano@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01460,FirstName:"Jeff",LastName:"Carter",Email:"jcarter@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01414,FirstName:"Aldo",LastName:"Castro",Email:"acastro@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00575,FirstName:"Deen",LastName:"Cawthon",Email:"dcawthon@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01441,FirstName:"Adan",LastName:"Cervantes",Email:"acervantes@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01104,FirstName:"Pablo",LastName:"Cervantes",Email:"pcervantes@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01293,FirstName:"Charles",LastName:"Chapman",Email:"cchapman@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01002,FirstName:"Seneca",LastName:"Chapman",Email:"schapman@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00933,FirstName:"Alan",LastName:"Chen",Email:"achen@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00623,FirstName:"Vic",LastName:"Christensen",Email:"vchristensen@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01410,FirstName:"Michael",LastName:"Christian",Email:"mchristian@amada.com"),
            AS400_SALESMAN(SalesmanNumber:05583,FirstName:"Patrick",LastName:"Clement",Email:"pclement@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01366,FirstName:"Chancy",LastName:"Cockrum",Email:"ccockrum@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00934,FirstName:"Mark",LastName:"Coffey",Email:"mcoffey@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01332,FirstName:"James",LastName:"Cole",Email:"jcole@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00774,FirstName:"Bob",LastName:"Cole",Email:"bcole@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01105,FirstName:"John",LastName:"Conniff",Email:"jconniff@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06001,FirstName:"Frank",LastName:"Corigliano",Email:"fcorigliano@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01338,FirstName:"Joey",LastName:"Cotero",Email:"jcotero@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06039,FirstName:"Benjamin",LastName:"Couture",Email:"bcouture@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01220,FirstName:"Clay",LastName:"Cox",Email:"ccox@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01433,FirstName:"Ian",LastName:"Crane",Email:"icrane@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01263,FirstName:"Marcos",LastName:"Cruz",Email:"mcruz@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01385,FirstName:"Robert",LastName:"Dailey",Email:"rdailey@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00943,FirstName:"Graham",LastName:"Dallas",Email:"gdallas@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00695,FirstName:"Ali",LastName:"Danesh",Email:"adanesh@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01383,FirstName:"Manuel",LastName:"Davila",Email:"mdavila@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01379,FirstName:"James",LastName:"Davis",Email:"jamesdavis@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00911,FirstName:"Steve",LastName:"Davis",Email:"sdavis@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01443,FirstName:"Jason",LastName:"Davis",Email:"jdavis@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01162,FirstName:"Mike",LastName:"DeCono",Email:"mdecono@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01446,FirstName:"Thomas",LastName:"DeMarco",Email:"tomdemarco@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01292,FirstName:"Rex",LastName:"DePedro",Email:"rdepedro@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06010,FirstName:"Anthony",LastName:"Desmas",Email:"adesmas@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:06032,FirstName:"Daniel",LastName:"Di Gregorio",Email:"dgregorio@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:00937,FirstName:"Mike",LastName:"DiPasqua",Email:"mdipasqua@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01429,FirstName:"Muriel",LastName:"DiPasqua",Email:"mbeardipasqua@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01300,FirstName:"Dustin",LastName:"Diehl",Email:"ddiehl@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06033,FirstName:"David",LastName:"Domanski",Email:"ddomanski@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01435,FirstName:"Fernando",LastName:"Dominguez",Email:"fdominguez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01277,FirstName:"Shane",LastName:"Douglas",Email:"sdouglas@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01347,FirstName:"Matthew",LastName:"Dubach",Email:"mdubach@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06024,FirstName:"Mario",LastName:"Duhamel",Email:"mduhamel@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:06011,FirstName:"James",LastName:"Duo",Email:"jduo@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01151,FirstName:"Charles",LastName:"Duran",Email:"cduran@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01335,FirstName:"Paul",LastName:"Dynak",Email:"pdynak@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01458,FirstName:"EZEKIEL",LastName:"ENRIQUEZ",Email:"eenriquez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00967,FirstName:"Bradley",LastName:"Edmark",Email:"bedmark@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00951,FirstName:"Jon Paul",LastName:"Edwards",Email:"jedwards@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01235,FirstName:"Kyle",LastName:"Edwards",Email:"kedwards@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01364,FirstName:"Andrew",LastName:"Eirich",Email:"aeirich@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01143,FirstName:"William",LastName:"Eirls",Email:"weirls@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01348,FirstName:"David",LastName:"Ellis",Email:"dellis@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01102,FirstName:"Dave",LastName:"Erickson",Email:"derickson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01408,FirstName:"Maite",LastName:"Escamilla",Email:"mescamilla@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01228,FirstName:"Roberto",LastName:"Escobedo",Email:"rescobedo@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01367,FirstName:"LEONARD",LastName:"FIORONI",Email:"lfioroni@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00912,FirstName:"Todd",LastName:"Fansler",Email:"mfansler@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01470,FirstName:"Jerry",LastName:"Farley",Email:"jfarley@amada.com"),
            AS400_SALESMAN(SalesmanNumber:05341,FirstName:"Gordon",LastName:"Faulkner",Email:"gfaulkner@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01107,FirstName:"John",LastName:"Felice",Email:"jfelice@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01301,FirstName:"Jason",LastName:"Flanner",Email:"jflanner@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01275,FirstName:"James",LastName:"Flores",Email:"jflores@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01199,FirstName:"Derrick",LastName:"Flores",Email:"dflores@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00869,FirstName:"Jay",LastName:"Floyd",Email:"afloyd@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06012,FirstName:"Denis",LastName:"Fontaine",Email:"fontaine@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01419,FirstName:"Tyler",LastName:"Fontanilla",Email:"tfontanilla@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06013,FirstName:"Bernard",LastName:"Fournier",Email:"bfournier@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01195,FirstName:"Larry",LastName:"France",Email:"lfrance@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00593,FirstName:"Dan",LastName:"Frederiksen",Email:"dfrederiksen@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01362,FirstName:"Joseph",LastName:"Funderburg",Email:"jfunderburg@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00850,FirstName:"Brian",LastName:"Gallivan",Email:"bgallivan@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01400,FirstName:"Tracy",LastName:"Galloway",Email:"tgalloway@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01418,FirstName:"Jose",LastName:"Garcia",Email:"jgarcia@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01266,FirstName:"Justin",LastName:"Garland",Email:"jgarland@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01304,FirstName:"Daniel",LastName:"Garza",Email:"dgarza@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00839,FirstName:"Brian",LastName:"Gassett",Email:"bgassett@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01428,FirstName:"Brian",LastName:"Gibson",Email:"bgibson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01158,FirstName:"Anthony",LastName:"Gilbert",Email:"agilbert@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01344,FirstName:"Juan",LastName:"Godoy",Email:"jgodoy@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01403,FirstName:"Ivan",LastName:"Gomez",Email:"igomez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00833,FirstName:"Manny",LastName:"Gonzales",Email:"mgonzales@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01324,FirstName:"Mario",LastName:"Gonzalez",Email:"mgonzalez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00909,FirstName:"Lewis",LastName:"Gordon",Email:"lgordon@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01424,FirstName:"Colby",LastName:"Grabill",Email:"cgrabill@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01461,FirstName:"Marshall",LastName:"Graham",Email:"mgraham@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01472,FirstName:"Libby",LastName:"Graves",Email:"lgraves@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00960,FirstName:"Joseph",LastName:"Greeninger",Email:"jgreeninger@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00895,FirstName:"Casey",LastName:"Greer",Email:"cgreer@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06034,FirstName:"Ulric",LastName:"Guerette",Email:"uguerette@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01296,FirstName:"Jason",LastName:"Guerin",Email:"jguerin@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01190,FirstName:"Greg",LastName:"Guinto",Email:"gguinto@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01390,FirstName:"Alice",LastName:"Gutierrez",Email:"agutierrez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01393,FirstName:"Gabriel",LastName:"Guzman",Email:"gguzman@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01388,FirstName:"Marco",LastName:"Guzman-Hernandez",Email:"mghernandez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01159,FirstName:"Laura",LastName:"Haas",Email:"lhaas@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01236,FirstName:"Michael K.",LastName:"Harewood",Email:"mharewood@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01321,FirstName:"Ryan",LastName:"Hart",Email:"rhart@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01369,FirstName:"Timothy",LastName:"Hauske",Email:"thauske@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01449,FirstName:"Garin",LastName:"Hedberg",Email:"ghedberg@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01256,FirstName:"Miguel",LastName:"Hernandez",Email:"mhernandez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00968,FirstName:"James",LastName:"Hill",Email:"jhill@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00898,FirstName:"Jason",LastName:"Hillenbrand",Email:"jhillenbrand@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01436,FirstName:"Michael",LastName:"Hoeft",Email:"mhoeft@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01161,FirstName:"Joseph",LastName:"Horbenko",Email:"jhorbenko@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01466,FirstName:"Jeb",LastName:"Howard",Email:"jhoward@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00117,FirstName:"Alden",LastName:"Hunt",Email:"ahunt@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01342,FirstName:"Ahmed",LastName:"Issa",Email:"aissa@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01405,FirstName:"Robert",LastName:"Jacot",Email:"rjacot@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01204,FirstName:"Tim",LastName:"Jancosko",Email:"tjancosko@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01394,FirstName:"Kieko",LastName:"Johnson",Email:"kjohnson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01469,FirstName:"Joshua",LastName:"Jones",Email:"jjones@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06030,FirstName:"Andrew",LastName:"Jones",Email:"ajones@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01073,FirstName:"Chris",LastName:"Jurgensen",Email:"cjurgensen@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00595,FirstName:"Tony",LastName:"Karam",Email:"tkaram@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01178,FirstName:"Michael",LastName:"Karuga",Email:"mkaruga@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00996,FirstName:"Lawrence",LastName:"Kearney",Email:"lkearney@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00510,FirstName:"Steve",LastName:"Keating",Email:"skeating@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06002,FirstName:"Luke",LastName:"Kerr",Email:"kerr@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01173,FirstName:"Jonathan",LastName:"Kim",Email:"jkim@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01459,FirstName:"Joseph",LastName:"Kloeker",Email:"jkloeker@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00938,FirstName:"Rob",LastName:"Kolaczewski",Email:"rkolaczewski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01153,FirstName:"Bill",LastName:"Kramer",Email:"wkramer@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01217,FirstName:"Christopher",LastName:"Krineski",Email:"ckrineski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01376,FirstName:"Michael",LastName:"Kroger",Email:"mkroger@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01374,FirstName:"Charles",LastName:"Kurilko",Email:"ckurilko@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01452,FirstName:"DAVID",LastName:"LAGACE",Email:"dlagace@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06026,FirstName:"Ken",LastName:"Lafleur",Email:"klafleur@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01377,FirstName:"David",LastName:"Lampe",Email:"dlampe@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06038,FirstName:"Jet",LastName:"Lee",Email:"jlee@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01343,FirstName:"Michael",LastName:"Lefebvre",Email:"mlefebvre@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01297,FirstName:"Alvaro",LastName:"Lemus",Email:"alemus@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06003,FirstName:"Ricky",LastName:"Levesque",Email:"levesque@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01341,FirstName:"Dean",LastName:"Lewis",Email:"deanlewis@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06015,FirstName:"Paul",LastName:"Lewis",Email:"plewis@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:06016,FirstName:"Benjamin",LastName:"Li",Email:"bli@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:05363,FirstName:"Filander",LastName:"Lima",Email:"flima@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01336,FirstName:"Sean",LastName:"Linnhoff",Email:"slinnhoff@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06041,FirstName:"David",LastName:"Liu",Email:"dliu@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01316,FirstName:"Rhea",LastName:"Lloyd",Email:"rlloyd@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01319,FirstName:"Mike",LastName:"Loger",Email:"mloger@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01474,FirstName:"James",LastName:"Lohstroh",Email:"jlohstroh@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01361,FirstName:"Angel",LastName:"Lopez",Email:"alopez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00817,FirstName:"Sam",LastName:"Lozano",Email:"slozano@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01406,FirstName:"Bryce",LastName:"Luman",Email:"bluman@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01317,FirstName:"RANDALL",LastName:"MORA",Email:"rmora@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01184,FirstName:"Kim",LastName:"Magdangal",Email:"kmagdangal@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01389,FirstName:"Vinodh",LastName:"Makayee",Email:"vmakayee@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01134,FirstName:"Ronald",LastName:"Malinowski",Email:"rmalinowski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01169,FirstName:"Manny",LastName:"Malk",Email:"mmalk@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01386,FirstName:"Richard",LastName:"Manetti",Email:"rmanetti@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01231,FirstName:"Efrain",LastName:"Martinez",Email:"emartinez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01399,FirstName:"Karl",LastName:"Mason",Email:"kmason@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06029,FirstName:"Jason",LastName:"Matijasich",Email:"jmatijasich@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01140,FirstName:"Ashley",LastName:"Matthis",Email:"amatthis@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01450,FirstName:"Jeffrey",LastName:"McCombs",Email:"jmccombs@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01284,FirstName:"Ronald",LastName:"McConnell",Email:"rmcconnell@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01363,FirstName:"Christopher",LastName:"McGuire",Email:"cmcguire@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01378,FirstName:"John",LastName:"McNamara",Email:"jmcnamara@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06006,FirstName:"Gannon",LastName:"McSween",Email:"gmcsween@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01427,FirstName:"Nick",LastName:"Mead",Email:"nmead@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01426,FirstName:"Patrick",LastName:"Medlin",Email:"pmedlin@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01229,FirstName:"Tooling Sales",LastName:"Mexico",Email:""),
            AS400_SALESMAN(SalesmanNumber:01097,FirstName:"Jeffrey",LastName:"Michael",Email:"jmichael@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01215,FirstName:"Matt",LastName:"Milazzo",Email:"mmilazzo@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01453,FirstName:"Ronald",LastName:"Miller",Email:"rmiller@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01439,FirstName:"William",LastName:"Milliken",Email:"wmilliken@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01421,FirstName:"Matthew",LastName:"Milton",Email:"mmilton@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01167,FirstName:"Hitoshi",LastName:"Miyake",Email:"hmiyake@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01462,FirstName:"Roy",LastName:"Moore",Email:"rmoore@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01451,FirstName:"Jason",LastName:"Moore",Email:"jmoore@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01437,FirstName:"Valdemar",LastName:"Morales",Email:"vmorales@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01395,FirstName:"Maria",LastName:"Moralez",Email:"mmoralez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01150,FirstName:"Jeff",LastName:"Morrow",Email:"jmorrow@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01415,FirstName:"Jonathan",LastName:"Munoz",Email:"jmunoz@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01358,FirstName:"Edgar",LastName:"Murillo",Email:"emurillo@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00807,FirstName:"Don",LastName:"Murphy",Email:"dmurphy@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01368,FirstName:"AUGIE",LastName:"NIETO",Email:"anieto@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06031,FirstName:"Jean-Philippe",LastName:"Nadeau",Email:"jpnadeau@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01246,FirstName:"Mark",LastName:"Nawalany",Email:"mnawalany@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01467,FirstName:"Donald",LastName:"Neste",Email:"dneste@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01198,FirstName:"Clinton",LastName:"Newton",Email:"cnewton@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01333,FirstName:"Keith",LastName:"Norris",Email:"knorris@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01244,FirstName:"Ireneusz",LastName:"Nowak",Email:"inowak@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00802,FirstName:"Jim",LastName:"O'Neil",Email:"joneil@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01355,FirstName:"CHARLOTTE",LastName:"OPEN",Email:""),
            AS400_SALESMAN(SalesmanNumber:01356,FirstName:"BOSTON",LastName:"OPEN",Email:""),
            AS400_SALESMAN(SalesmanNumber:01357,FirstName:"COLUMBUS",LastName:"OPEN",Email:""),
            AS400_SALESMAN(SalesmanNumber:00886,FirstName:"Rob",LastName:"Ochs",Email:"rochs@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01283,FirstName:"Gregory",LastName:"Olsen",Email:"golsen@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01402,FirstName:"S Texas",LastName:"Open",Email:""),
            AS400_SALESMAN(SalesmanNumber:01260,FirstName:"*",LastName:"Open NW",Email:""),
            AS400_SALESMAN(SalesmanNumber:01116,FirstName:"*",LastName:"Open SE",Email:""),
            AS400_SALESMAN(SalesmanNumber:01416,FirstName:"Francisco",LastName:"Orozco",Email:"forozco@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06017,FirstName:"Greg",LastName:"Orr",Email:"gorr@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01434,FirstName:"Nathan",LastName:"Ostrowski",Email:"ostrowski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00957,FirstName:"Nick",LastName:"Ostrowski",Email:"nostrowski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01387,FirstName:"Michael",LastName:"Otten",Email:"motten@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01084,FirstName:"James",LastName:"Otten",Email:"jotten@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00812,FirstName:"Scott",LastName:"Ottens",Email:"sottens@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01164,FirstName:"Daniel",LastName:"Ouellette",Email:"douellette@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00508,FirstName:"Michael",LastName:"Palmer",Email:"mpalmer@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06025,FirstName:"Ranjit",LastName:"Panesar",Email:"rpanesar@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:06023,FirstName:"Martin",LastName:"Paradis",Email:"mparadis@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01120,FirstName:"John",LastName:"Parenzan",Email:"jparenzan@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01375,FirstName:"Harold",LastName:"Parslow",Email:"hparslow@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06042,FirstName:"Rakshesh",LastName:"Patel",Email:"rpatel@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:05241,FirstName:"Richard",LastName:"Patenaude",Email:"rpatenaude@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01149,FirstName:"Daniel",LastName:"Patterson",Email:"dpatterson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01340,FirstName:"Perrier",LastName:"Paul",Email:"ppaul@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01320,FirstName:"Dan",LastName:"Peay",Email:"dpeay@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00130,FirstName:"John",LastName:"Pence",Email:"jpence@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01422,FirstName:"Jose",LastName:"Pereyra",Email:"jpereyra@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01307,FirstName:"Esteban",LastName:"Perez",Email:"eperez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01318,FirstName:"Harris",LastName:"Pham",Email:"hpham@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01354,FirstName:"Liem",LastName:"Phan",Email:"lphan@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01128,FirstName:"Phillip",LastName:"Picardat",Email:"ppicardat@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06009,FirstName:"Corey",LastName:"Pimlatt",Email:"cpimlatt@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01417,FirstName:"Bryan",LastName:"Pollema",Email:"bpollema@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01457,FirstName:"Damian",LastName:"Porebski",Email:"dporebski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01174,FirstName:"Jack",LastName:"Qi",Email:"jqi@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01218,FirstName:"John",LastName:"Ramirez",Email:"jramirez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01392,FirstName:"Esperanza",LastName:"Ramirez",Email:"esramirez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00915,FirstName:"Eliseo",LastName:"Ramirez",Email:"eramirez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00828,FirstName:"Ron",LastName:"Reed",Email:"rreed@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01130,FirstName:"Kelly",LastName:"Richardson",Email:"krichardson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01468,FirstName:"Marisol",LastName:"Rivera",Email:"mrivera@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01471,FirstName:"Martin",LastName:"Rivera",Email:"marivera@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01398,FirstName:"Rocio",LastName:"Rivera",Email:"rrivera@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01259,FirstName:"Brian",LastName:"Rojas",Email:"brojas@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01249,FirstName:"Enrique",LastName:"Romero",Email:"eromero@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01420,FirstName:"Michael",LastName:"Roure",Email:"mroure@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06022,FirstName:"Tim",LastName:"Rozdeba",Email:"trozdeba@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:00738,FirstName:"Greg",LastName:"Rudigier",Email:"grudigier@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01325,FirstName:"Michael",LastName:"Ryan",Email:"mryan@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06037,FirstName:"James",LastName:"Sabayo",Email:"jsabayo@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01359,FirstName:"Diego",LastName:"Sanchez",Email:"dsanchez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01163,FirstName:"Fernando",LastName:"Sanchez",Email:"fsanchez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01448,FirstName:"Jason",LastName:"Sanders",Email:"jsanders@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01430,FirstName:"Maria",LastName:"Sasaki",Email:"msasaki@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00950,FirstName:"Chuck",LastName:"Savage",Email:"csavage@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01371,FirstName:"Richard",LastName:"Scavelli",Email:"rscavelli@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01476,FirstName:"Mark",LastName:"Schmideskamp",Email:"mschmideskamp@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00792,FirstName:"Steve",LastName:"Schneider",Email:"sschneider@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01444,FirstName:"Brian",LastName:"Schuler",Email:"bschuler@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01380,FirstName:"Daniel",LastName:"Schultz",Email:"dschultz@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01305,FirstName:"William",LastName:"Schumaker",Email:"wschumaker@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01289,FirstName:"Mike",LastName:"Sedlock",Email:"msedlock@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01350,FirstName:"Zach",LastName:"Severance",Email:"zseverance@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01327,FirstName:"Rick",LastName:"Severance",Email:"rseverance@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01464,FirstName:"Jake",LastName:"Sherman",Email:"jsherman@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06019,FirstName:"Tyler",LastName:"Shipowich",Email:"tshipowich@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:00830,FirstName:"Pat",LastName:"Shivers",Email:"pshivers@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00879,FirstName:"Jamie",LastName:"Sims",Email:"jsims@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00975,FirstName:"Brad",LastName:"Smith",Email:"bsmith@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01445,FirstName:"Diana",LastName:"Soto",Email:"dsoto@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01360,FirstName:"Oscar",LastName:"Soto",Email:"osoto@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01346,FirstName:"Ryan",LastName:"Stanage",Email:"rstanage@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01456,FirstName:"Michael",LastName:"Struzik",Email:"mstruzik@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01211,FirstName:"Dan",LastName:"Sturwold",Email:"dsturwold@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01423,FirstName:"Gabriel",LastName:"Suarez",Email:"gsuarez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01103,FirstName:"Jim",LastName:"Sun",Email:"jsun@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01270,FirstName:"Alicia",LastName:"Sylvia",Email:"asylvia@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06027,FirstName:"Chason",LastName:"Thompson",Email:"cthompson@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01175,FirstName:"Robert",LastName:"Tolentino",Email:"rtolentino@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01337,FirstName:"Juan",LastName:"Torres",Email:"juantorres@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01353,FirstName:"Michael",LastName:"Tran",Email:"mtran@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06040,FirstName:"Marc",LastName:"Tremblay",Email:"mtremblay@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01396,FirstName:"Daniel",LastName:"Tucker",Email:"dtucker@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01129,FirstName:"Ron",LastName:"Turcotte",Email:"rturcotte@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01397,FirstName:"Krzysztof",LastName:"Tylka",Email:"ktylka@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01431,FirstName:"Kei",LastName:"Uchikawa",Email:"kuchikawa@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01473,FirstName:"Keith",LastName:"Ustaszewski",Email:"kustaszewski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00903,FirstName:"Frank",LastName:"Vallone",Email:"fvallone@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01454,FirstName:"Alexander",LastName:"Van Oyen",Email:"avanoyen@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01179,FirstName:"Todd",LastName:"Vannieuwenhoven",Email:"tvannie@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01279,FirstName:"Dirseu (Isaac)",LastName:"Vasquez",Email:"dvasquez@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06018,FirstName:"Rene",LastName:"Verrier",Email:"rverrier@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01334,FirstName:"Leticia",LastName:"Villa",Email:"lvilla@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01254,FirstName:"David",LastName:"Villareal",Email:"dvillarreal@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01465,FirstName:"Alvin",LastName:"Viloria",Email:"aviloria@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01365,FirstName:"Dennis",LastName:"Wagner",Email:"dwagner@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00907,FirstName:"Bill",LastName:"Watkins",Email:"wwatkins@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00806,FirstName:"Mike",LastName:"Webber",Email:"mwebber@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00610,FirstName:"Mark",LastName:"Wenham",Email:"mwenham@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01302,FirstName:"Judah",LastName:"Wetherbee",Email:"jwetherbee@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01440,FirstName:"Brais",LastName:"Whirl",Email:"bwhirl@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00752,FirstName:"John",LastName:"Whitaker",Email:"jwhitaker@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01280,FirstName:"Paul",LastName:"Williford",Email:"pwilliford@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00918,FirstName:"Troy",LastName:"Wilson",Email:"dwilson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01326,FirstName:"Todd",LastName:"Wilson",Email:"twilson@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01425,FirstName:"Matt",LastName:"Winslow",Email:"mwinslow@amada.com"),
            AS400_SALESMAN(SalesmanNumber:06035,FirstName:"Sean",LastName:"Wismer",Email:"swismer@amada.ca"),
            AS400_SALESMAN(SalesmanNumber:01110,FirstName:"Paul",LastName:"Wojciechowski",Email:"pwojciechowski@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01111,FirstName:"Kerry",LastName:"Woodburn",Email:"wwoodburn@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00922,FirstName:"John",LastName:"Woodruff",Email:"jwoodruff@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01475,FirstName:"Xuefeng",LastName:"Wu",Email:"swu@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01401,FirstName:"Nicholas",LastName:"Yaekle",Email:"nyaekle@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00805,FirstName:"Christopher",LastName:"Yates",Email:"cyates@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01412,FirstName:"Hon-Lin",LastName:"Yu",Email:"hyu@amada.com"),
            AS400_SALESMAN(SalesmanNumber:00662,FirstName:"Dave",LastName:"Zaybal",Email:"dzaybal@amada.com"),
            AS400_SALESMAN(SalesmanNumber:01191,FirstName:"Mike",LastName:"Zordan",Email:"mzordan@amada.com")
        ]
    }
}
